server:
  port: 9993
  shutdown: graceful

spring:
  profiles:
    active: local
  config:
    import:
      - classpath:config/${spring.profiles.active}/redis.yml
      - classpath:config/${spring.profiles.active}/sa-token.yml
  application:
    name: websocket-service
